version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mystack-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1abak3xjm9shg"
s3_prefix = "mystack-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
